# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: pass
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
